### ISSUE TITLE
How to increase JVM heap size?

### ISSUE THREAD

**Issue by desertSniper87** [peasead/elastic-container#45]
How to increase the JVM heap size from 512m to 1G?

The official docs say this to pass as environment variable `-Xms1g -Xmx1g`: https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-stack-docker.html#docker-enroll-nodes

**Comment by desertSniper87** [comment]
We can change the heap size by editing `docker-compose.yml` and passing `ES_JAVA_OPTS` environment variable to elasticsearch container. 

```yml
  elasticsearch:
   ...
    environment:
+     - ES_JAVA_OPTS=-Xmx1g -Xms1g
```

Added a pull request to change the readme https://github.com/peasead/elastic-container/pull/46#issue-2378867303
